-- Apps conf ----------------------------
terminal = "urxvtc"
manager = "rox-filer"
editor = "vim"
editor_cmd = terminal .. " -e " .. editor
apparence = "lxappearance"
archiver = "file-roller"
guieditor = "geany"
filer = "rox-filer"
mediaplayer = "gnome-mplayer"
musicplayer = terminal .. " -e mocp"
irc = terminal .. "-T weechat -e weechat-curses"
burner = "brasero"
webcli = "luakit"
webgui = "firefox"
ftpgui = "gftp"
torrent = "transmission"
writer = "abiword"
tableur = "gnumeric"
calc = "xcalc"
pdf = "evince"
imageviewer = "gpicview"
locker = "slock"
-----------------------------------------
